import {test,expect} from '@playwright/test';
const paper={id:'2609.12345v1',title:'A new world model paper',authors:['Author One'],abstract:'The original abstract.',published:'2026-09-22T00:00:00Z',url:'https://arxiv.org/abs/2609.12345v1',pdfUrl:'https://arxiv.org/pdf/2609.12345v1'};
test('arXiv search uses the selected topic, shows original papers, and supports paging and sorting',async({page})=>{
 const requests:URL[]=[];
 await page.route('**/api/arxiv/search?*',async route=>{const url=new URL(route.request().url());requests.push(url);const start=Number(url.searchParams.get('start'));await route.fulfill({json:{papers:[paper],total:11,start,nextStart:start===0?10:null}});});
 await page.goto('/');
 await page.locator('#topics').getByRole('button',{name:'World Models',exact:true}).click();
 await page.getByRole('button',{name:'Find more on arXiv'}).click();
 const dialog=page.getByRole('dialog',{name:'Search arXiv'});
 await expect(dialog).toBeVisible();
 await expect(dialog.getByRole('heading',{name:/A new world model/})).toBeVisible();
 expect(requests[0].searchParams.get('q')).toBe('"world model"');
 expect(requests[0].searchParams.get('sort')).toBe('newest');
 await dialog.getByText('Read abstract',{exact:true}).click();
 await expect(dialog.getByText('The original abstract.')).toBeVisible();
 await expect(dialog.getByRole('link',{name:'Open PDF'})).toHaveAttribute('href',paper.pdfUrl);
 await dialog.getByRole('button',{name:'Next 10'}).click();
 await expect(dialog.getByRole('status')).toHaveText('11–11 of 11 matches');
 await dialog.getByLabel('arXiv result order').selectOption('relevance');
 await expect(dialog.getByRole('status')).toHaveText('1–1 of 11 matches');
 expect(requests.at(-1)?.searchParams.get('sort')).toBe('relevance');
 expect(requests.at(-1)?.searchParams.get('start')).toBe('0');
 await page.screenshot({path:'/tmp/arxiv-search-desktop.png'});
 await page.keyboard.press('Escape');
 await expect(dialog).not.toBeVisible();
 await expect(page.getByRole('button',{name:'Find more on arXiv'})).toBeFocused();
});
test('phone search gives clear empty and unavailable states without replacing the shelf',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 let fail=false;
 await page.route('**/api/arxiv/search?*',route=>route.fulfill(fail?{status:502,json:{error:'arXiv search is temporarily unavailable.'}}:{json:{papers:[],total:0,start:0,nextStart:null}}));
 await page.goto('/');
 await page.getByRole('button',{name:'Find more on arXiv'}).click();
 const dialog=page.getByRole('dialog');
 await expect(dialog.getByRole('status')).toContainText('No papers found');
 await page.screenshot({path:'/tmp/arxiv-search-mobile.png'});
 fail=true;
 await dialog.getByRole('button',{name:'Search',exact:true}).click();
 await expect(dialog.getByRole('alert')).toContainText('temporarily unavailable');
 await expect(dialog.getByRole('link',{name:'Open arXiv'})).toHaveAttribute('href',/^https:\/\/arxiv.org\/search\//);
 const box=await dialog.boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(390);
 await dialog.getByRole('button',{name:'Close arXiv search'}).click();
 await expect(page.locator('.shelf-book')).toHaveCount(6);
});
