"use client";

import { Check, ExternalLink, RefreshCw, X } from "lucide-react";
import { useState } from "react";

type ReviewPaper = { id:string; title:string; abstract:string|null; arxiv_id:string|null; arxiv_url:string|null; relevance_score:number; relevance_terms:string[]; published_at:string|null; authors_json:string[]; github_url:string|null; citation_count:number|null };

export function ReviewQueue({ initialPapers }: { initialPapers: ReviewPaper[] }) {
  const [papers,setPapers]=useState(initialPapers); const [secret,setSecret]=useState(""); const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState("");
  async function decide(id:string,status:"published"|"rejected") { if(!secret){setMessage("Enter the editorial secret first.");return} setBusy(id); const response=await fetch(`/api/review/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/json"},body:JSON.stringify({status})}); if(response.ok){setPapers(items=>items.filter(item=>item.id!==id));setMessage(status==="published"?"Paper published.":"Paper rejected.")}else { const result=await response.json().catch(()=>({})); setMessage(result.error || "Could not update this paper."); } setBusy(null) }
  return <div className="review-shell"><div className="review-toolbar"><div><b>{papers.length}</b><span>papers awaiting review</span></div><label>Editorial secret<input type="password" value={secret} onChange={event=>setSecret(event.target.value)} placeholder="CRON_SECRET"/></label></div>{message&&<p className="review-message">{message}</p>}<div className="review-list">{papers.map(paper=><article key={paper.id}><div className="review-score"><b>{Math.round(paper.relevance_score*100)}</b><span>match</span></div><div className="review-main"><div className="tags">{paper.relevance_terms.slice(0,4).map(term=><span key={term}>{term}</span>)}</div><h2>{paper.title}</h2><p>{paper.abstract}</p><small>{paper.authors_json.join(", ")} · {paper.published_at?.slice(0,4)}</small><div className="review-links">{paper.arxiv_url&&<a href={paper.arxiv_url} target="_blank">arXiv <ExternalLink/></a>}{paper.github_url&&<a href={paper.github_url} target="_blank">GitHub <ExternalLink/></a>}{paper.citation_count!==null&&<span>{paper.citation_count} citations</span>}</div></div><div className="review-actions"><button disabled={busy===paper.id} onClick={()=>decide(paper.id,"published")}><Check/> Publish</button><button disabled={busy===paper.id} onClick={()=>decide(paper.id,"rejected")}><X/> Reject</button>{busy===paper.id&&<RefreshCw className="spin"/>}</div></article>)}{papers.length===0&&<div className="review-empty"><Check/><h2>You’re caught up.</h2><p>No papers currently need editorial review.</p></div>}</div></div>;
}
